
format:
  revealjs:
    smaller: true
    theme: [default, ../custom.scss, slides.scss]     
    # theme: [default, ../custom.scss]     
    mainfont: "Helvetica"
    html-math-method: mathjax
    # section-divs: true
    # include-in-header:
    # - text: |
    #     <script>
    #       Reveal.initialize({ plugins: [RevealMath.MathJax3] });
    #     </script>

execute:
  freeze: auto
  echo: false
  fig-format: svg  


project:
  output-dir: ../_build/slides  
  render:
    - index.qmd
    # # - "**/*.qmd"  # render all qmd files
    # # - "**/*.ipynb"  # render all qmd files
    # # - "!draft-*.qmd"  # except those starting with draft-
    # - "!./internals/"  # exclude entire directories
    # - "!./pages/benchmarks/**"
    # - "!./pages/popgen/"
    # - "!./pages/topics/R/"
    # - "!./mathref/*.qmd"
    # - "!./pages/vignettes/"  